# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ['nombre_estado'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('1', 'Norte'), ('2', 'Occidente'), ('3', 'Centro'), ('4', 'Sur')], default='1', max_length=1)),
                ('tipo', models.CharField(choices=[('1', 'Pública'), ('2', 'Particular')], max_length=1)),
                ('estatus', models.CharField(choices=[('1', 'Acreditada'), ('2', 'Aspirante')], max_length=1)),
                ('acreditacion', models.CharField(blank=True, default='2016', max_length=4)),
                ('nombre_escuela', models.CharField(max_length=75)),
                ('nombre_campus', models.CharField(blank=True, max_length=50)),
                ('nombre_director', models.CharField(max_length=50)),
                ('mail_contacto', models.EmailField(max_length=50)),
                ('domicilio', models.CharField(max_length=150)),
                ('sitio_web', models.URLField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Estado')),
            ],
            options={
                'verbose_name_plural': 'Facultades',
                'ordering': ['entidad', 'region', 'institucion', 'nombre_campus'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_universidad', models.CharField(max_length=80)),
                ('nombre_rector', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre_universidad'],
            },
        ),
        migrations.AddField(
            model_name='facultad',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Institucion'),
        ),
    ]
